### ISSUE TITLE
stdout\stderr error when installing one specific mod

### ISSUE THREAD

**Issue by Owyn** [wrye-bash/wrye-bash#362]
```
Traceback (most recent call last):
  File "bash\balt.pyo", line 2435, in __Execute
  File "bash\balt.pyo", line 1563, in _conversation_wrapper
  File "bash\basher\installer_links.pyo", line 543, in Execute
  File "bash\bosh\__init__.pyo", line 6200, in bain_install
  File "bash\bosh\__init__.pyo", line 6175, in _install
  File "bash\bosh\__init__.pyo", line 5131, in install
  File "bash\bolt.pyo", line 927, in moveTo
  File "bash\bolt.pyo", line 887, in remove
WindowsError: [Error 5] : u's:\\users\\owyn\\appdata\\local\\temp\\WryeBash_mvd8y6\\Data\\meshes\\actors\\character\\animations'

```

mod: http://www.nexusmods.com/skyrimspecialedition/mods/3761/?

**Comment by Utumno** [comment]
That's fixed in current wip - hit refresh on the mod before trying though

**Comment by Owyn** [comment]
@Utumno I have Wrye Bash 307 beta1 installed (current wip, no?), tried hitting refresh on the mod, then install but still same error:
![55](https://cloud.githubusercontent.com/assets/1309656/22550758/9bab7f46-e962-11e6-9402-72ede238cd3e.png)

**Comment by Owyn** [comment]
@Utumno 
to be specific it gives installation error when "slayer" packages are selected (08 and 11)

**Comment by Utumno** [comment]
No the current wip is in the second post of the oblivion thread (read the readme here)

**Comment by Owyn** [comment]
@Utumno 
Nope, still the same bug in newer version I got from 2nd post (307 WB wip standalone link), readme didn't help anyhow.

**Comment by Utumno** [comment]
The readme was for the links to beta - did you hit refresh ? Try removing
and readding the installer

**Comment by Owyn** [comment]
I did hit the refresh button.

> Try removing and readding the installer

woah, that actually worked, thx.

**Comment by Utumno** [comment]
Which refersh did you hit ?

**Comment by Owyn** [comment]
The one which has text "refresh" on it?...

Right click on the mod - refresh in context menu
