### ISSUE TITLE
Always show an error on gui on startup crash

### ISSUE THREAD

**Issue by Utumno** [wrye-bash/wrye-bash#373]
Aka never crash silently. We have reports of people that try to use Bash and it crashes silently for them - and who knows how many had this and never reported it

- [x] use showErrorInAnyGui
- [x] add a link to the official thread

Under #244

**Comment by D4id4los** [comment]
I had a look at this and from what I have seen all paths through `bash.main()` should give some error message, but none use `_showErrorInAnyGui()`, most use `_showErrorInGui()` while `oneInstanceChecker()` uses its own error message implementation. Do you want all of those changed to use `_showErrorInAnyGui()`?

With regards to links to the official thread I could only find two posts ([#1](https://bethesda.net/community/post/307489) and [#2](https://bethesda.net/community/post/379234)) but none of those come with a bug dump.

**Comment by Utumno** [comment]
Hey @D4id4los - I haven't looked at the implementation - I want as big a part of main to be caught up in a try except (define a method) but not too big. Give it a whirl on a branch on dev. `oneInstanceChecker` I don't really like btw - _showErrorInAnyGui is called in _showErrorInGui, the difference is we try to use balt/basher if we can - we tried harder before but I simplified it recently to reduce complexity.

So the logic is import wx -> balt -> basher -> show our dialogs else wx and if that fails Tkinter.

Should be wrapped in `try: _main except: _showErrorInAnyGui` - but as I said there are many details in there. Anyway we do need this ASAP - that is before next "I launch Bash and nothing happens" report.

See also commits in #244

**Comment by Utumno** [comment]
The simplification commit: "This commit also drops the balt/basher part of _showErrorInGui.." - c75fd17408c858e440ebc558ed3089e4a26d4a4f - see commits and comments in #244 - so if wx fails then Tkinter, if balt/basher fails then wx else Bash custom showError style dialogs

**Comment by Utumno** [comment]
Basically moving the Tkinter error handling inside `_import_wx()` eliminatig those ugly _wx would be an idea

**Comment by Utumno** [comment]
We still need to dump_environment - need some elegant solution to this

**Comment by Utumno** [comment]
Now back to my esl work ;)

**Comment by D4id4los** [comment]
Alright i'll have a look at making a reasonable try-catch block for errors.

**Comment by Utumno** [comment]
Inline main (rename in _main and call in main, will keep diff readable) in try and move Tkinter stuff in _import_wx() my first thought - call dump_environment(None) in there also. I also have a well defined refactoring task I want done btw - see #300.

**Comment by Utumno** [comment]
>  in there also

In except ImportError that is

**Comment by Utumno** [comment]
Or most accurately have a "Please post this to link or link (both threads)" and then the contents of bugdump - some dump_environment refactoring needed to return a string

**Comment by D4id4los** [comment]
I just pushed an attempt at this refactoring to [daidalos-373-always-show-errors](https://github.com/wrye-bash/wrye-bash/tree/daidalos-373-always-show-errors) in commit b997fa3f35c2de04b5a9589a7e2c077de95be521. Does this look like what you had in mind?

**Comment by Utumno** [comment]
@D4id4los - there are still rough edges here:

- starting Bash from the Debug.bat if an exception is raised after the BashFrame is instantiated the process remains in memory - here are my attempts at a monkey patch that didn't fix it https://github.com/wrye-bash/wrye-bash/commit/fa48931bb2c92d7edcfc6ece57200638f7e94cf9
That's not limited to the bat but it's most prominent there. Didn't try standalone
- also this:
  > Need to fix debug bat - as it is raising the exception in basher results in Found Python at 'C:\_\Python27\pythonw.exe' Launching Wrye Bash 307 in debug mode Cannot launch Wrye Bash because another instance is already running Press any key to continue . . . Note "because another instance is already running"
  see https://github.com/wrye-bash/wrye-bash/commit/03218382be7c8f7217340ea45742f8c1847b1b26

It would be great if you could hava a look in the weekend as I would like this in for the beta (scheduled for Christmas more or less)

**Comment by D4id4los** [comment]
@Utumno Would you look at that, just as you comment I am already working on it ;). As seen in the timeline https://github.com/wrye-bash/wrye-bash/commit/7636fcd0d3ea952b3924d7d86bebbfbbf97f9957 should fix the debug batch issue (albeit with a kludge: it will print an empty line instead of a error, but I don't know batch well enough to do better).

I'll try to investigate the first problem right now.

**Comment by D4id4los** [comment]
Okay, as for Wrye Bash remaining in memory when an exception is thrown during init of BashFrame I have determined that it is not an issue of the wx frames not getting closed correctly. You can try yourself: if you comment out the call to _show_wx_error() and just close Wrye Bash with sys.exit(1) everything works fine.

Somehow after the first exception is thrown, all subsequent calls to a wx.App.MainLoop() function cause the thread to freeze no matter what I do. I tried manually closing all other Frames and Apps before, re-importing wx, and creating different dialog boxes. This has me quite stumped, so I'll try to think of something else to try out tomorrow

**Comment by Utumno** [comment]
> (albeit with a kludge: it will print an empty line instead of a error, but I don't know batch well enough to do better).

Hahaha - that's just good enough!

Yep booting is complex - looking forward to your solution. I am not clear myself about booting wx logic. Probably the error dialog itself should be Detroyed() ? Or put the BashFrame() out of the try/except ?

**Comment by Utumno** [comment]
I went ahead and pushed the beta - wanted to have it on christmas - I could not postpone it any longer. But I intend to publish 307 soon so this will be in that. Thanks - and merry christmas 🎅

**Comment by D4id4los** [comment]
I found out that changing the error message box from using a wx.Frame to using a wx.Dialog could be used to fix the issue and to be honest this seems to be a more sensible approach to me anyway, but I am not sure if there was any deeper reason for using a frame instead of a dialog. 

Can you think of any reason? If not then I have a working implementation committed in af558d0555de418ead3cf3b536b6efd0b5809956.

**Comment by Utumno** [comment]
The only thing I can think of is that before the wx app is instantiated (or whatever) probably we need a frame - I guess the dialog is a part of an App ? Just test what happens if you raise an Exception at various points in boot - if it's ok then let's call it a day. Question: why is the cleanup of windows needed in `_show_wx_error` ? Wasn't that done before ?

**Comment by D4id4los** [comment]
I'll test it more throughoutly, but using a dialog seems to fix the issue. 

The cleanup wasn't done before. In fact I put it in because for me the splash screen would cover the error message (even in the old implementation). But you do raise a good point: Doing it in _show_wx_error does not make much sense from a logical perspective. I'll go look for a more sensible place to put this.

**Comment by Utumno** [comment]
Thanks @D4id4los. All those commits belong together, so when we finish reviewing could you just squash them together with the main one editing the commit message as you see fit ? I have already done this with the first commits ( f93d900c665be6bf683a614202e076983d18003b ) - leave the last part of the message (my changes) I will edit it myself. Probably some of it belongs to comments (just a couple terse comments)

Pheew - proved a hard nut (kind of expecting it, booting is always complex plus wx stuff)

**Comment by D4id4los** [comment]
Alright, I made a _close_dialog_windows() function in commit 36d3cc91c72122599014cf96d07ed0c57c75bf4a and tested the fix with ~20 exceptions at different points in the code.

If it looks alright to you I'll squash the commits together and you can incorporate it into utumno-wip.

**Comment by Utumno** [comment]
Go for it - the only think that maybe needs be done is a `if basher is None: return` check in `_close_dialog_windows()`. Also a couple terse comments on the if check line 463.  Just also edit the commit message as you see fit so I can then merge to dev - if you want you can incorporate my comments or leave that to me (I mean squash all the commits together - easier by cherrypicking the main commit over dev and then the others)

A hard nut :)

**Comment by D4id4los** [comment]
I wasn't quite sure what changes to your comments you wanted me to make, but I hope I did alright with me squashing everything into 3f812f0cdc2df41424949bbabc93e05ee473d3ad.
I wanted to do this myself to learn the more involved ways of using git. Tell me if I made some mistake with it and I'll try to fix it.

**Comment by Utumno** [comment]
No mistakes but basically you could omit all the rest of the commits on that branch (before and after that one) - done this here: https://github.com/wrye-bash/wrye-bash/commits/373-always-show-errors-DEV If you are satisfied with the commit message we are good to go ( I need to merge some other stuff in first) - I removed a `# raise Exception` I had left in and still have to edit the message to really mention the issues, but this I will do before merging (actually cherry picking) to dev

Should I prune the rest of the 373 branches on the upstream ? You should have local copies already

**Comment by D4id4los** [comment]
Sure go ahead.

**Comment by Utumno** [comment]
Late to the party but here are a couple links of interest:

https://stackoverflow.com/questions/6234405/logging-uncaught-exceptions-in-python
https://pymotw.com/2/sys/exceptions.html

We might consider replacing the wx excepthook or define our own from the beginning at some point in the future - should be cleaner and immune to most of the freezing issues

**Comment by D4id4los** [comment]
It sound like something to be considered in the future. Do you want me to make a new enhancement issue that is marked backburner for this one so we don't forget?

**Comment by Utumno** [comment]
No need thanks, we can always work on it if need be - glad you get my twisted issue logic btw :)

Or better - add a note in #300 which is a dump for ideas like this - will edit a bit ASAP, for now is just a glimpse in the chaos of my local TODOs

Another edge case that was fixed in latest iterations, but sheds some light to peculiar frame loading etc - add a raise Exception in `setBsaRedirection` - before Bash would load _and_ display the quit dialog (which did not quit) - now quits. Have a look, we may after all need more work for 307 - but I think this is good enough for dev, will merge

Thanks :)
