### ISSUE TITLE
Enderal Support

### ISSUE THREAD

**Issue by Infernio** [wrye-bash/wrye-bash#433]
## Introduction
[Enderal](https://enderal.com/), a total conversion mod for Skyrim by [SureAI](https://sureai.net/), has been [released as a standalone game on Steam](https://store.steampowered.com/app/933480/Enderal_Forgotten_Stories/). It's implemented as a Skyrim installation with custom masters as well as SKSE and a bunch of SKSE plugins preinstalled.

### A Word of Warning
The information in this issue is my understanding of the situation. Things may be incorrect or incomplete. If you notice something that's wrong or missing, feel free to comment.

## Current Status
Pretty much all the basics as well as many advanced features are done.
In particular, things that are known to work include:
- Installing mods
- Managing the load order
- Building a Bashed Patch
- INI tweaks
- Inspecting and managing saves
- Inspecting and managing screenshots

What is needed right now is testing from a bigger crowd (i.e. a nightly release with this code in it) as well as some more work to inspect the remaining advanced features and see how much of it is feasible.
In particular, things that need more testing include:
- Installing complex mods (wizards, etc.)
- Building Bashed Patches with many features enabled - I'm especially interested in the Tweak Settings patcher.

For more detailed information, see the checklists below as well as my branch, [inf-enderal](https://github.com/wrye-bash/wrye-bash/tree/inf-enderal).

## Basic Info
Enderal uses an SKSE plugin called [SkyrimRedirector](https://github.com/Davipb/SkyrimRedirector) in order to have its own, distinct `My Games` and `AppData` directories. This allows using it alongside a Skyrim installation.

As of the latest update, its launcher creates a registry entry at `HKEY_CURRENT_USER\Software\SureAI\Enderal\Install_Path`, which Wrye Bash can actually already check, so no extra work is needed there.

xEdit has added support for Enderal in the testing version `4.0.1l`. Support will land in the stable `4.0.2` release, which is likely only a few days away from release at the time of writing.

### Engine
As already mentioned, Enderal is based on Skyrim's engine. This means it shares almost all internals with Skyrim, including its record definitions, form versions, etc.

### Paths
- AppData: `%LocalAppData%/enderal`
- My Games: `My Games\Enderal`

### Master Files
- `Skyrim.esm`
- `Update.esm`
- `Enderal - Forgotten Stories.esm`

They should be in exactly that order, and all of them should always be activated. Note that although Enderal shares the names `Skyrim.esm` and `Update.esm` with Skyrim, their contents are vastly different.

### INIs
- Default INI: `enderal_default.ini`
- Default Prefs INI: `EnderalPrefs_default.ini`
- User INI: `Enderal.ini`
- User Prefs INI: `EnderalPrefs.ini`

### Vanilla Files
The following list has been generated via `find . -type f | cut -d'/' -f 2- | sed -e "s/^/u'/; s/$/',/; s./.\\\\\\\.g"` in Git Bash:
https://gist.github.com/Infernio/4b8e2551bb157f21db9e45b6822744e7

## Checklist - Basic Support
- [ ] **Update the documentation!**
- [x] Create `bash/game/enderal` and update all necessary variables. This will get WB to recognize Enderal as a game it can manage.
- [x] Create icons for it - without those, WB crashes on launch.
  - Done by extracting them from the launcher.
- [x] Create an empty taglist for it - without one, WB crashes on launch.
- [x] Update `bash/game/enderal/constants.py` to override `bethDataFiles` with the list of vanilla files above. This will allow WB to clean the data directory when requested.
- [x] Edits to the NSIS installer script so that it installs Wrye Bash into Enderal's install directory. I don't have the slightest clue about how to write NSIS though.

## Checklist - Advanced Features
- [x] Create an EnderalEdit launcher.
  - [x] ~~**Note:** Commented out default INI entries are still missing from `bash_default.ini` and `bash_default_Russian.ini`.~~ - **Done in https://github.com/wrye-bash/wrye-bash/commit/e16be2034573ca0bc1f568a273a225012b87c0db**.
- [x] Enable all Skyrim-specific features for Enderal as well (e.g. BSA reading, Savegame reading, Bashed Patch building, etc.)
- [x] Update INI tweaks for Enderal - while no additions or deletions are necessary, some defaults are different.
- [x] Create a custom taglist for Enderal based on the Skyrim one, or wait for the LOOT team to make one. Without such a taglist, the Bashed Patch breaks the vanilla masters.

## Checklist - Open Questions, Problems and Hiccups
- [x] Enderal and Skyrim both ship `TESV.exe`, which is what is currently used for command-line game detection, causing unpredictable behavior when the `-o` parameter is used to specify Enderal.
  - **Done by properly reworking exe-based game detection in https://github.com/wrye-bash/wrye-bash/commit/c69d5e60aad92a93ec630d1a6a07b680fdc89b1e.**
- [x] ~~'Clean Data Directory' causes Enderal to crash and must be force-disabled.~~
  - Not anymore - Enderal fixed this in Feburary 2019.
- [x] SKSE logging isn't actually redirected to `My Games\Enderal`, it still goes to `My Games\Skyrim`. This shouldn't be a problem for WB however, we don't seem to expose any functionality for reading those files. Note #456 though, which will need to consider this.

## Future Work (308+)
- [ ] [raceHairMale and raceHairFemale](https://github.com/wrye-bash/wrye-bash/commit/c592089d4a2881b2e8c20d3ddd9c42d06a6d39e9#diff-259749112eb2b08696ed3d17217d0184R74) haven't been updated yet - but as far as I can tell, those are actually specific to saves-related code that only works for Oblivion(?), so I don't know why the other games even overwrite it.
- [ ] Does `bash/db/Skyrim_ids.pkl` need updating? Running the program meant to update them just spat out a `No update needed` message, so I assume not?
- [ ] The load order specified above should always be fixed and the plugins should always be force-activated.
  - *Partially done in https://github.com/wrye-bash/wrye-bash/commit/bc796538abcded2040daed15b15307323ecbd547,* but doesn't yet work correctly. This commit should be left out of any nightly releases, since it blocks users from manually fixing screwed up load orders.

**Comment by Infernio** [comment]
Before this makes it into a nightly, I'd like to at least try to make a custom taglist for it, based on the Skyrim one. Otherwise, building a BP is going to be a nightmare.

**Comment by Infernio** [comment]
Update on this experiment: I made a custom taglist, but using that caused the BP to throw really strange GUI errors. After investigating further, it somehow picked up some FormIDs as integers from Enderal's masters.

Even more investigation revealed that Enderal's NAVI records are broken - their FormIDs are apparently `00000000`. Both xEdit and WB completely give up at this and just spit out errors, so I don't feel too bad :P

**Comment by Infernio** [comment]
Updating with discoveries made on the Discord in the last few days:

Looks like the `'int' object has no attribute 'startswith'` error really just an ancient problem that's resurfacing.
From Utumno on Discord:
> \> AttributeError: 'int' object has no attribute 'startswith'
>
> This was a very elusive bug that apparently manifested again - see https://github.com/wrye-bash/wrye-bash/issues/95 - which really brings us to https://github.com/wrye-bash/wrye-bash/issues/312
>
> \> * Investigate why we instantiate the gui panels once
>
> This is a cashe invalidation issue, which is one of the two major issues in programming along naming and fence-post errors. Another manifestation:
> https://github.com/wrye-bash/wrye-bash/issues/113

**Comment by Utumno** [comment]
Bear in mind that this may _not_ be the ancient problem but a new one - just in case it's the ancient one however that was tricky so I mentioned. If it appears consistently the second time a user builds the patch then probably it's the ancient one.

**Comment by Verayth** [comment]
As I mentioned on AFK Mods, managing Saves Profiles isn't working. The SavePath Enderal.ini setting needs to redirect from Skyrim to the Enderal Saves Folder.  Changing the profile with Wrye Bash removes "..\Enderal\" from the beginning of the relative path:

[General]
SLocalSavePath=..\Enderal\Saves\<Profile Name>

**Comment by Infernio** [comment]
@Verayth Should be fixed as of 5925393a0124d33dbb52a6e81cbf9a84c3a6b3af, could you test that one?

**Comment by Infernio** [comment]
Some further investigation into the Bashed Patch building issue:
This problem seems to disappear if I remove the `Stats` tag from `Enderal - Forgotten Stories.esm`. No other tags seem to matter, I have it tagged with just about everything else, and building the BP works fine.

No idea what the cause is, but that's the 'hotfix' I'll use for now.

**Comment by Verayth** [comment]
The Profile save path issue is fixed, and Enderal loads and saves from profile folders just fine.  The Masters pane was unstable for a bit until I enabled each profile individually and then quit and re-started Wrye Bash.

**Comment by Verayth** [comment]
Uninstalling an active Steam Workshop mod with Enderal Launcher causes this error on launching Wrye Bash.
```
Traceback (most recent call last):
  File "bash\bash.py", line 184, in main
    _main(opts)
  File "bash\bash.py", line 362, in _main
    app.Init() # Link.Frame is set here !
  File "bash\basher\__init__.py", line 4009, in Init
    self.InitData(progress)
  File "bash\basher\__init__.py", line 4046, in InitData
    bosh.modInfos.refresh(booting=True)
  File "bash\bosh\__init__.py", line 1856, in refresh
    forceRefresh=hasChanged or _modTimesChange, forceActive=deleted)
  File "bash\bosh\__init__.py", line 1603, in _modinfos_cache_wrapper
    lord_func(self, *args, **kwargs)
  File "bash\bosh\__init__.py", line 1711, in refreshLoadOrder
    cached_active=not forceActive)
  File "bash\load_order.py", line 303, in refresh_lo
    _update_cache(lo, active)
  File "bash\load_order.py", line 255, in _update_cache
    cached_lord = LoadOrder(lord, acti_sorted)
  File "bash\load_order.py", line 97, in __init__
    [x.s for x in (set(active) - set(loadOrder))]))
BoltError: Active mods with no load order: SkipIntro.esp

```
Launching Wrye Bash a second time gives a different error after Wrye Bash cleans the esp from loadorder.txt, but it still exists in plugins.txt.  The launcher only removes it after you hit "Data Files"->"Save changes".  The game itself is unaffected by the non-existent ESP in plugins.txt.  You get this same error if you install a new Steam Workshop mod and then use the Enderal Launcher to move it up in the load order.  The error goes away if you move it back to the bottom of the load order.
```
Traceback (most recent call last):
  File "bash\bash.py", line 184, in main
    _main(opts)
  File "bash\bash.py", line 362, in _main
    app.Init() # Link.Frame is set here !
  File "bash\basher\__init__.py", line 4009, in Init
    self.InitData(progress)
  File "bash\basher\__init__.py", line 4046, in InitData
    bosh.modInfos.refresh(booting=True)
  File "bash\bosh\__init__.py", line 1856, in refresh
    forceRefresh=hasChanged or _modTimesChange, forceActive=deleted)
  File "bash\bosh\__init__.py", line 1603, in _modinfos_cache_wrapper
    lord_func(self, *args, **kwargs)
  File "bash\bosh\__init__.py", line 1711, in refreshLoadOrder
    cached_active=not forceActive)
  File "bash\load_order.py", line 303, in refresh_lo
    _update_cache(lo, active)
  File "bash\load_order.py", line 253, in _update_cache
    fix_lo)
  File "bash\games.py", line 227, in get_load_order
    cached_active_ordered)
  File "bash\games.py", line 246, in _cached_or_fetch
    cached_active)
  File "bash\games.py", line 682, in _fetch_load_order
    to = w[ordered] + 1 + j
KeyError: bolt.Path(u'SkipIntro.esp')

```

**Comment by Utumno** [comment]
> Uninstalling an active Steam Workshop mod with Enderal Launcher causes this error on launching Wrye Bash.

So the plugin is deleted and plugins.txt still contains it? Probably loadorder.txt is purged but not the plugins.txt by Bash - this may be an error

**Comment by Verayth** [comment]
Yes, errors when it still exists in plugins.txt and not on file, or recently installed and moved up in load order via launcher.  so 2 slightly different issues.

**Comment by Utumno** [comment]
For loadorder.txt games the deal was IIRC user must use any of the tools that are aware of loadorder.txt for managing her load order. Still we should be able to recover (not CTD)

**Comment by Infernio** [comment]
After some more experiments with the Enderal BP, the issue only occurs when using the `Stats` tag on `Enderal - Forgotten Stories.esm`. [This commit](https://github.com/wrye-bash/wrye-bash/commit/bd554cd91d80e7d8c1bfdafbff4d2c61906727e7) seems to fix the issue, allowing the `Stats` tag to be used.

Some further investigation shows that this does indeed occur because of the critical effects of a few records in `Enderal - Forgotten Stories.esm`:
 - `000EA29C`
 - `0101C742`
 - `0101EB8E`
 - `01024151`

Manually removing the critical effects from these in xEdit also fixes the issue.
I'll try to make a minimal reproducing plugin for Skyrim.

**Comment by Infernio** [comment]
Here is a plugin (for Skyrim LE) that reproduces the issue reliably: [test.zip](https://github.com/wrye-bash/wrye-bash/files/2920680/test.zip)

Drop the zip into the Installers tab and install, move it before the BP in the Mods tab and rebuild the BP. You should get the now-familiar error message.

**Comment by Arthmoor** [comment]
It wasn't known until very recently that the critical effects data was even used at all since no vanilla records for LE or SSE actually set it. It's valid if used by a mod though and the game treats it just as you'd expect. So it probably just never came up for Skyrim until now because nobody else uses it either.

**Comment by Utumno** [comment]
Well it's simple then - the criticalEffect was defined with an integer default while it should be a string - probably a long id. 

As I pointed out (see that #423 commit etc) we need to carry the criticalEffect , which means that we need some code that performs correct comparisons - that's probably not trivial. The solution of ommiting it is not good as a mod we included in the patch may depend on that criticalEffect override

10 miles high

**Comment by Arthmoor** [comment]
The actual effect specified is a form ID for a SPEL record.

**Comment by Verayth** [comment]
The Nexus URL for Enderal mods needs an update.  There's now a slash required between enderal and mods.
`https://www.nexusmods.com/enderal/mods/19`

**Comment by Infernio** [comment]
Whoops, fixed in https://github.com/wrye-bash/wrye-bash/commit/67e1d03f94ebf8f31c5a585888971283d4df29fc

**Comment by Verayth** [comment]
wow, that was quick.  much better thank you!

**Comment by Infernio** [comment]
@Utumno I was just looking at adding installer support for Enderal, when I noticed this: https://github.com/wrye-bash/wrye-bash/blob/735c43607db77f4d55807fac67068638c6280545/scripts/build/installer/install.nsi#L379-L389

It looks like that got copied from FO4, but incorrectly - shouldn't it be like this:
```patch
diff --git a/scripts/build/installer/install.nsi b/scripts/build/installer/install.nsi
index 9fa40ce4..14f5b3d1 100644
--- a/scripts/build/installer/install.nsi
+++ b/scripts/build/installer/install.nsi
@@ -379,11 +379,11 @@
                 ${If} $CheckState_FalloutNV_Py == ${BST_CHECKED}
                     CreateShortCut "$SMPROGRAMS\Wrye Bash\Wrye Bash - FalloutNV.lnk" "$Path_FalloutNV\Mopy\Wrye Bash Launcher.pyw" "" "$Path_FalloutNV\Mopy\bash\images\bash_32.ico" 0
                     CreateShortCut "$SMPROGRAMS\Wrye Bash\Wrye Bash - FalloutNV (Debug Log).lnk" "$Path_FalloutNV\Mopy\Wrye Bash Debug.bat" "" "$Path_FalloutNV\Mopy\bash\images\bash_32.ico" 0
-                    ${If} $CheckState_Fallout4_Exe == ${BST_CHECKED}
+                    ${If} $CheckState_FalloutNV_Exe == ${BST_CHECKED}
                         CreateShortCut "$SMPROGRAMS\Wrye Bash\Wrye Bash (Standalone) - FalloutNV.lnk" "$Path_FalloutNV\Mopy\Wrye Bash.exe"
                         CreateShortCut "$SMPROGRAMS\Wrye Bash\Wrye Bash (Standalone) - FalloutNV (Debug Log).lnk" "$Path_FalloutNV\Mopy\Wrye Bash.exe" "-d"
                     ${EndIf}
-                ${ElseIf} $CheckState_Fallout4_Exe == ${BST_CHECKED}
+                ${ElseIf} $CheckState_FalloutNV_Exe == ${BST_CHECKED}
                     CreateShortCut "$SMPROGRAMS\Wrye Bash\Wrye Bash - FalloutNV.lnk" "$Path_FalloutNV\Mopy\Wrye Bash.exe"
                     CreateShortCut "$SMPROGRAMS\Wrye Bash\Wrye Bash - FalloutNV (Debug Log).lnk" "$Path_FalloutNV\Mopy\Wrye Bash.exe" "-d"
                 ${EndIf}
```

**Comment by Utumno** [comment]
Most probably yes - I am not familiar with that code. Btw when you edited for removing gimpshop that should also go to the "delete files from older versions" section (from the look I had to that there)

**Comment by Infernio** [comment]
You mean like this?
```patch
diff --git a/scripts/build/installer/macros.nsh b/scripts/build/installer/macros.nsh
index 86fa060b..a0ab44af 100644
--- a/scripts/build/installer/macros.nsh
+++ b/scripts/build/installer/macros.nsh
@@ -197,6 +197,9 @@
         Delete "${Path}\Mopy\bash\images\gimp16.png"
         Delete "${Path}\Mopy\bash\images\gimp24.png"
         Delete "${Path}\Mopy\bash\images\gimp32.png"
+        Delete "${Path}\Mopy\bash\images\gimpshop16.png"
+        Delete "${Path}\Mopy\bash\images\gimpshop24.png"
+        Delete "${Path}\Mopy\bash\images\gimpshop32.png"
         Delete "${Path}\Mopy\bash\images\gmax16.png"
         Delete "${Path}\Mopy\bash\images\gmax24.png"
         Delete "${Path}\Mopy\bash\images\gmax32.png"
@@ -542,6 +545,9 @@
         Delete "${Path}\Mopy\bash\patcher\utilities.p*"
         ; As of 307, the following are obsolete:
         Delete "${Path}\Mopy\bash\compiled\loot32.dll"
+        Delete "${Path}\Mopy\bash\images\tools\gimpshop16.png"
+        Delete "${Path}\Mopy\bash\images\tools\gimpshop24.png"
+        Delete "${Path}\Mopy\bash\images\tools\gimpshop32.png"
         Delete "${Path}\Mopy\bash\loot.py"
         ; And some leftovers from various releases, some of them only appeared on dev:
         Delete "${Path}\Mopy\INI Tweaks\Skyrim\Archery, NavMeshMove 4096 -Default [Skyrim].ini"
```
I don't really understand the NSIS stuff either - I managed to [copy-paste enough to get the installer working for Enderal](https://github.com/wrye-bash/wrye-bash/commit/37d7d928a95b47da18b0b13a6f7fd2aa61e284cc), but that's just about it for my experience with NSIS :P

**Comment by Utumno** [comment]
I guess this would do - @DianaNites had started a python installer which was a hack IIRC but at some point we should get rid of all this copy paste thing. But priority is of course the python code always :)

**Comment by DianaNites** [comment]
Started, never finished, and I don't believe I have any of the code still around. Less a python installer and more an installer generator. Tell python the files, generate an installer that handles them for the right games.

That said, these days I don't really play Fallout/Skyrim anymore. Or Python, for that matter, these days I program in Rust.

**Comment by Utumno** [comment]
Hi there @DianaNites glad you're still around :)

**Comment by DianaNites** [comment]
Wouldn't really say "still around", i check github and this was in my notifications, but other than that 🤷‍♀️

**Comment by Infernio** [comment]
With the [proper fix for the critical effect issue](https://github.com/wrye-bash/wrye-bash/commit/8581423bbc95048a6feb7025ff3c4df3a519e117), Enderal support is now pretty stable - probably stable enough to include in a nightly, in fact.

**Comment by Utumno** [comment]
Feel free to include stuff in the nightly as you see fit - have some nightlies posted in the discord/dropbox so usual ~~suspects~~ testers give them a whirl - then update nexus.

**Comment by Utumno** [comment]
https://www.nexusmods.com/enderal/mods/97 -> what is your username over there (gosh their UX is pretty bad, spent like 10 minutes to find how to create a file)

**Comment by Infernio** [comment]
[Infernio](https://www.nexusmods.com/users/4354257), same as everywhere else

**Comment by Utumno** [comment]
I added you everywhere then :)

**Comment by Infernio** [comment]
@Utumno `inf-433-enderal` is done. The readme diffs are a bit unreadable because I refactored a lot in there to make them more maintainable in the future - sorry about that. Note that I dropped the taglist, wasn't all that useful since almost no mod actually conflicts with the Enderal masters. Just uses the Skyrim taglist now, which also means we save ~15000 lines of YAML.

**Comment by Utumno** [comment]
Alea jacta est @Infernio - this has been sitting on nightly for ages so let's merge it :)

(No worries about the readmes, after the feles merge I swore I will never look into readme diffs for one year counting from today)
