### ISSUE TITLE
Support Windows Store versions of games

### ISSUE THREAD

**Issue by lojack5** [wrye-bash/wrye-bash#585]
The Windows Store version of Skyrim Special Edition doesn't play nice right now.  It's installed to the Program Files\ModifiableWindowsApps location, which has some special write permissions.  The main folder we cannot write to (without some serious permission editing - more than just taking ownership, etc), but subfolders (ie: the Data folder) are perfectly writable.

MSStore apps function very differently than we're used to:

1. The actual data files for the program are stored in a virtual file system, called a `PackageVolume`, which are stored in single files per volume under `WindowsApps\MSIXVC`.  You can query the registry to see what Package Volumes exist, they're listed in the key `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\PackageVolumes`.  Subkeys and nodes there give information about where the volume shows up as a directory in the file system.
2. We can query the `InstallLocation` for these apps with some Powershell commands:
  -  `Get-AppxPackage | Where-Object {$_.publisherid -eq "3275kfvn8vcwc" } | Select Name, InstallLocation` queries for all apps from Bethesda (3275kfvn8vcwc is their PublisherID).
  -  `Get-AppxPackage | Where-Object {$_.name -Like "*SkyrimSE*" } |Select Name, InstallLocation` queries for all apps with a name containing "SkyrimSE" in it.  We can use logical operators to combine this with the above if there are problems with non-Bethesda apps that have the game name in them (maybe mods on the windows store?).
  - In the registry under, well, *many* locations: `HKEY_CLASSES_ROOT\Local Settings\Software\Microsoft\Windows\CurrentVersion\AppModel\PackageRepository\Packages\BethesdaSoftworks.SkyrimSE-PC_1.11.0.0_x64__3275kfvn8vcwc` for example.
3. The location that is *writable* is the `ModifiableWindowsApps\{game folder}` location.  This again points into the virtual file system, so takes up no actual space in the real file system.  However, editing/writing files will create actual files there (which override the ones in the virtual filesystem).
4. ~~We can find the Modifiable folder by determining the InstallLocation, then "going up" one directory and looking for a ModifiableWindowsApp directory, then finding the game directory in there.~~ This actually doesn't work in all cases.  See the wiki for the updated method.
5. Load order is stll in a `plugins.txt`, but this edition looks for it in two locations:
  - `%LOCALAPPDATA%\Skyrim Special Edition MS\Plugins.txt`
  - `%LOCALAPPDATA%\Packages\BethesdaSoftworks.SkryimSE-PC_3275kfvn8vcwc\LocalCache\Local\Skyrim Special Edition MS`
  It seem that if the Packages one is not present, then the first is read in for Load Order, but then deleted/moved to the Packages directory.  So we need to handle this case.

[Wiki Page](https://github.com/wrye-bash/wrye-bash/wiki/[dev]-Microsoft-Store-Games)

Other changes:
- The My Games folder is `My Games\Skyrim Special Edition MS`
- The Game folder is `Skyrim Special Edition (PC)`
Note: different names, so we can't use `GameInfo.fsName` for both of these.

There are file permission issues involved: it's very hard to get write access to the top level of ModifiableWindowsApps, as well as WindowsApps (all of it).  So we have to use (currently) as `bash.ini` to move the `Skyrim Special Edition Mods` folder out of those protected areas.  The relavent ini entries are `sOblivionMods`, `sBashModData`, and `sInstallersData`.

OK, action items:
- [x] Write the code that parses the registry to finds the installed
- [x] Write the code that parses the registry to find the games' mutable locations
- [x] Split `GameInfo.fsName` into two attributes, one for the game folder, one for the my games folder
- [x] Write code to handle two possible `plugins.txt` location: Read from Packages location first, fallback to the usual location. Always write to the Packages location.
- [x] Deal with Morrowind and Oblivion language variations: each language has a seperate install as a subfolder of the main install.
- [x] ~~Figure out if we can use IFileOperation only for changing modification time~~ Maybe...IFileOperation seems a non-starter.  We could instead move the file to a location on the same drive outside of the protected locations, modify the times, then move them back.   This would be the most efficient IO wise, but is not atomic.  The safer "atomic-like" operation would be to *copy* the file to a non-protected location, modify it, then move it into the game directory.  I'm marking this one as a "put off til later" issue.  We don't have a good non-admin way to modify times, and admin mode works.
- [x] The vanilla files need updating, SSE, FO4, Morrowind, and Oblivion ship all the files for all languages now (we should have done that before, poor non-English users :P)
- [x] Implement a method to determine game version that does not rely on reading the EXE for the game (EXE files are non-accessible even for the mutable location).  The easiest way will probably be to modify `WinStoreFinder` to read in all possible information about a windows store app, the version is accessible in the registry.
- [x] Use the above version detection to implement `CompareGameVersion` in Wizard scripts.
- [x] Use the above version detection to implement version detection in FOMOD scripts.
- [x] Update the Readme with applicable information, and common errors/issues that can pop up when managing a WS game.

**Comment by Infernio** [comment]
Do we even have registry keys for detecting this version?

The SKSE team also isn't sure if they'll be able to make SKSE (and the other xSEs, while we're at it) work for this version. Apparently the main EXE is very locked down, so the way that xSE usually injects itself doesn't work.

**Comment by Infernio** [comment]
> %LOCALAPPDATA%\Packages\BethesdaSoftworks.SkyrimSE-PC_3275kfvn8vcwc\LocalCache\Local\Skyrim Special Edition MS\Plugins.txt

Regarding this, can we trust that to stay in the same place? If not, we should have it list the `%LOCALAPPDATA%\Packages` directory and look for ones starting with `BethesdaSoftworks.SkyrimSE-PC`.

**Comment by Infernio** [comment]
Apparently it also has a different `My Games` subfolder? Shadow said it creates a `Skyrim Special Edition MS` folder in there. Not sure how we handle this, probably we need a new game constant and need to make SSE MS an entirely different game in WB?

**Comment by Infernio** [comment]
Overall, this isn't quite as bad as I expected this to be, but it's still godawful. Thanks MS.

**Comment by Infernio** [comment]
OK, the other games look to be out as well. That would mean adding five new games (Morrowind MS, Oblivion MS, Fallout NV MS, Skyrim SE MS and Fallout 4 MS). Do we want to do that, or do we want to rethink this approach?

**Comment by Utumno** [comment]
It all looks like game handling has the focus now - #584 landed just on time :)

Seems we need new games yes, while working on reducing files/overrides. Another alternative that might pay in the long run is adding logic for detecting "flavours" of the game - so logic in GameInfo - detect based on keys _and_ scanning the ModifiableWindowsApps?

**Comment by Infernio** [comment]
This also makes #572 relevant, since even once we do support this people will still have to edit the INI. But I'm not sure the code is anywhere close to ready to support that issue yet.

**Comment by lojack5** [comment]
Yeah, everything you discovered looks about right Infernio.  I wasn't aware that ALL of the games got released, ugh.

I wonder if there's a non-UWP API to the microsoft store app that would help in detecting these.  Otherwise we'll have to fall back to scanning, and then that might be the ONLY way to tell the difference between windows store and non-windows store versions.

**Comment by lojack5** [comment]
Had another thought, we might be able to detect via running a powershell command if the game is a windows store version, investigating that now.

**Comment by lojack5** [comment]
Ok, we can detect game installs from MS store:

```
PS C:\Windows\System32\WindowsPowerShell\v1.0> Get-AppxPackage | Where-Object {$_.name -Like "*Skyrim*"}


Name              : BethesdaSoftworks.SkyrimSE-PC
Publisher         : CN=21E520D9-F467-4438-A16E-79ADDBE4ECB1
Architecture      : X64
ResourceId        :
Version           : 1.11.0.0
PackageFullName   : BethesdaSoftworks.SkyrimSE-PC_1.11.0.0_x64__3275kfvn8vcwc
InstallLocation   : C:\Program Files\WindowsApps\BethesdaSoftworks.SkyrimSE-PC_1.11.0.0_x64__3275kfvn8vcwc
IsFramework       : False
PackageFamilyName : BethesdaSoftworks.SkyrimSE-PC_3275kfvn8vcwc
PublisherId       : 3275kfvn8vcwc
IsResourcePackage : False
IsBundle          : False
IsDevelopmentMode : False
NonRemovable      : False
Dependencies      : {Microsoft.VCLibs.140.00.UWPDesktop_14.0.29231.0_x64__8wekyb3d8bbwe,
                    Microsoft.DirectXRuntime_9.29.952.0_x64__8wekyb3d8bbwe}
IsPartiallyStaged : False
SignatureKind     : Store
Status            : Ok
```

**Comment by lojack5** [comment]
Note, this has to be done with the base powershell (python subprocess, use "powershell.exe" as the command), not the MS updated powershell, as that doesn't work with Get-AppxPackage, there's a whole issue tracker open about it.

**Comment by lojack5** [comment]
We can detect MS versions by looking for `appxmanifest.xml` in the root folder of the game install, among other things.

**Comment by Utumno** [comment]
Good thing is we have a package now for this rather specific windoz stuff

**Comment by lojack5** [comment]
And here we go, this is probably what we'll want to use in the long run to not call into powershell multiple times:  Lists all apps installed by Bethesda

```
PS C:\Windows\System32\WindowsPowerShell\v1.0> Get-AppxPackage | Where-Object { $_.publisherid -eq "3275kfvn8vcwc" } | Select Name, InstallLocation

Name                          InstallLocation
----                          ---------------
BethesdaSoftworks.SkyrimSE-PC C:\Program Files\WindowsApps\BethesdaSoftworks.SkyrimSE-PC_1.11.0.0_x64__3275kfvn8vcwc
```

**Comment by lojack5** [comment]
OK, this is annoying, we won't have a nice programatic way of finding the actual folders we want to write to for the MS versions, at least as far as I can tell.

MS is using a virtual file system located inside `WindowsApps`:
![actual data](https://user-images.githubusercontent.com/1458329/111051438-d6e68080-8407-11eb-800d-9916171fab46.png)
These files are then linked to by the "Install Location":
![install folder](https://user-images.githubusercontent.com/1458329/111051447-e49c0600-8407-11eb-9826-3c9dba12dc44.png)
And by the ModifiableWindowsApps folder, which is where we should be reading/writing mods to:
![modifiable folder](https://user-images.githubusercontent.com/1458329/111051452-f2518b80-8407-11eb-9ba8-c8cd8815309f.png)
This isn't using the usual hard links, soft links, or even NTFS junctions.

The problem is, from Powershell we can only get the InstallLocation, I haven't been able to find a way to gather the modifiable location.  So it looks like we can use Powershell to *detect* that the game is installed, but the best bet we have to determine the write location is using `%PROGRAMFILES%\ModifiableWindowsApps\{game folder}`.

**Comment by lojack5** [comment]
There is a *little* bit of info in the registry:

![apps volumes](https://user-images.githubusercontent.com/1458329/111051637-78220680-8409-11eb-9288-b671d628a96d.png)
This indicates that the package volume 1 is located at C:\Program Files\Windows Apps, which is a parent directory of the InstallLocation for my SSE.  It has a sub-node `MutablePackagesOnline` which indicates that there is also a ModifiableWindowsApps folder associated with it, but again doesn't give the location.  M$ why you make this so complicated?

**Comment by Infernio** [comment]
Can we rely on the drive letter of the InstallLocation matching the drive letter of the ModifiableWindowsApps folder?

If so, I say we modify bush's game detection to call that powershell command, extract the drive letter, then ask each supported game if it has a Windows Store version (maybe abstract here - see @Utumno's remark about 'flavors') and check if [Drive letter]:\Program Files\ModifiableWindowsApps\[MS version name specified as a game constant for the we're checking for] exists.

Then for each game that we find such a path for, we add it to _allGames and store the path in a dict similar to _registryGames (or rename _registryGames and use it for both? Probably separate is better, will let us deprint them separately too). Then bush can take the games and paths, do its regular game detection/selection and hand off back to bash.py.

Throw some logic into bash.py/initialization.py to change the [Game] Mods default paths when a Windows Store game has been selected (bass var?) and we should be able to handle everything. 

That would leave only the plugins.txt path, not sure if it's hardcoded yet or how to retrieve it otherwise.

**Comment by lojack5** [comment]
I think we can rely on that, but no idea for sure.  I'd say use the powershell command to get `{some path here}\WindowsApps\BethesdaSoftworks.SkyrimSE-PC_1.11.0.0_x64__3275kfvn8vcwc`, then extract the `{some path here}` from that, tack on the `ModifiableWindowsApps` and then the applicable game folder.  So something like `Path.head.head.join('ModifiableWindowsApps', '{game_specific_directory}')`.

**Comment by lojack5** [comment]
Ok, did some digging with Process Monitor:
![plugins txt](https://user-images.githubusercontent.com/1458329/111059471-ae33aa80-844a-11eb-8ab9-20ced9abbfbc.png)
SSE-MS looks for a plugins.txt in two locations:
- The usual `AppData\Local\Skyrim Special Edition MS\Plugins.txt`
- The new `AppData\Local\Packages\BethesdaSoftworks.SkyrimSE-PC_3275kfvn8vcwc\LocalCache\Local\Skyrim Special Edition MS`

From some initial testing it seems the one in the Packages directory is used always if present.  If not present, then the one from the "usual" location is read for initial information, but then moved/deleted/recreated in the Packages directory.

I still need to test if modification times on these affect which one "wins".

**Comment by Infernio** [comment]
Started working on it in `inf-585-windows-store`.

**Comment by Infernio** [comment]
```
windows.py  661 get_win_store_game_path: _find_win_store_games took 0.421000s
```
It's cached, but still... ouch. 0.4s penalty to boot, just to call the powershell command.

**Comment by Infernio** [comment]
I'm speechless:

![image](https://user-images.githubusercontent.com/2845240/111066708-bdedd600-84c0-11eb-997b-dd33261674bf.png)

This is the output I get from the PS command with the MS Store version of Morrowind installed. It *truncates* the path 🙃

**Comment by Infernio** [comment]
@lojack5 Our method doesn't work. I chose to install a game (Morrowind) to my `E:` drive. It's indeed there:

![image](https://user-images.githubusercontent.com/2845240/111067202-73ba2400-84c3-11eb-82a7-fb68f74d35bb.png)

But the PS command returns:
```
Name                              InstallLocation
----                              ---------------
BethesdaSoftworks.TESMorrowind-PC C:\Program Files\WindowsApps\BethesdaSoftworks.TESMorrowind-PC_1.0.0.0_x86__3275kfvn8vcwc
```

Meanwhile the `C:\Program Files\ModifiableWindowsApps` folder is empty.

**Comment by Infernio** [comment]
That's not everything either: note the `Morrowind GOTY {English,French,German}` folders above. Each one is its own entirely separate Morrowind installation, which includes a separate Data Files folder. So we also need a way to determine which language version of the game to use at each given moment.

**Comment by lojack5** [comment]
Haven't fully woken up, was gonna work on this later today (nice to see you're already started).  Try reading from the registry instead, looks like this key might work, dunno if you'll hit the same problem though:

`HKEY_CLASSES_ROOT\Local Settings\Software\Microsoft\Windows\CurrentVersion\AppModel\PackageRepository\Packages\BethesdaSoftworks.SkyrimSE-PC_1.11.0.0_x64__3275kfvn8vcwc\Path`

Modifying of course for the applicable game.

**Comment by Infernio** [comment]
Also resolves to `C:\Program Files\WindowsApps\BethesdaSoftworks.TESMorrowind-PC_1.0.0.0_x86__3275kfvn8vcwc`.

**Comment by lojack5** [comment]
If that doesn't work, then it really sucks, but I think we can get away with reading

`HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\PackageVolumes`

And enumerating the volumes listed there, that should give all possible "WindowsApps" locations.  Will probably destroy startup times, but I'm not sure if there's any other way to get the location except force the users to specify it.

**Comment by Infernio** [comment]
It must somehow be possible to retrieve it if the MS Store can 'Open Mods Folder' just fine.

**Comment by Infernio** [comment]
I'm searching through my registry now, will edit this comment with everything I find.

- `Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\AppModel\StateRepository\Cache\Package\Data\9a9\MutableLocation` has it.

**Comment by lojack5** [comment]
I'll check back later this afternoon, yeah keep digging.  MutableLocation sounds promissing as long as we can figure out where that `9a9` came from.  I just looked at that last key I linked, it doesn't give the mutable location, and it's not "next to" the WindowsApps folder on my computer (on my D: drive).  

compatibility assistant and last typed won't be reliable unfortunately.

**Comment by Infernio** [comment]
Pushed my code for now, probably won't be able to do much more today.

**Comment by Infernio** [comment]
I think I found a map to those package indices. @lojack5 Could you check `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\AppModel\StateRepository\Cache\Package\Index\PackageFullName`? It should have a subkey for the game (in my case `BethesdaSoftworks.TESMorrowind-PC_1.0.0.0_x86__3275kfvn8vcwc`), and that has a subkey with the package index (`9a9` in my case).

**Comment by Infernio** [comment]
I still think there *has* to be a higher-level API for this. This is absurdly hacky, there's no way MS does this for their store.

**Comment by Infernio** [comment]
```
bush.py   88 _supportedGames: Wrye Bash looked for games in the following places:
bush.py   89 _supportedGames:  1. Windows Registry:
bush.py   91 _supportedGames:   The following installed games were found via the registry:
bush.py   94 _supportedGames:    Enderal: G:\steam\steamapps\common\Enderal
bush.py   94 _supportedGames:    Fallout 3: G:\steam\steamapps\common\Fallout 3 goty
bush.py   94 _supportedGames:    Fallout 4: G:\steam\steamapps\common\Fallout 4
bush.py   94 _supportedGames:    Fallout New Vegas: G:\steam\steamapps\common\Fallout New Vegas
bush.py   94 _supportedGames:    Oblivion: G:\steam\steamapps\common\Oblivion
bush.py   94 _supportedGames:    Skyrim: G:\steam\steamapps\common\Skyrim
bush.py   94 _supportedGames:    Skyrim Special Edition: G:\steam\steamapps\common\Skyrim Special Edition
bush.py  100 _supportedGames:   Make sure to run the launcher of each game you installed through Steam
bush.py  100 _supportedGames:   once, otherwise Wrye Bash will not be able to find it.
bush.py  101 _supportedGames:  2. Windows Store
bush.py  103 _supportedGames:   The following installed games with modding enabled were found via the Windows Store:
bush.py  106 _supportedGames:    Morrowind: E:\Program Files\ModifiableWindowsApps\Morrowind GOTY (PC)
bush.py  113 _supportedGames:   Make sure to enable mods for each Windows Store game you have
bush.py  113 _supportedGames:   installed, otherwise Wrye Bash will not be able to find it.
```

🎉

**Comment by Infernio** [comment]
Calling it a day for now, code is pushed. Next step is figuring out how to tell which language we should use (see my screenshot in https://github.com/wrye-bash/wrye-bash/issues/585#issuecomment-798893530) so that we can pass the right Data folder back to bash. If that turns out to be too hard/impossible, we can always show a popup/offer a CLI switch too.

**Comment by Utumno** [comment]
Amazing work @lojack5 @Infernio - from my part I am finalizing the parsers stuff to clean nightly as much as possible

**Comment by lojack5** [comment]
Nice, that's what I just discovered looking at it too.  I'll see if I can crack the language problem (doesn't happen on the Skyrim MS Store version), downloading Morriwind now to do testing.

**Comment by lojack5** [comment]
I found a slight improvement to finding the mutable location, we can get the package full name (which includes architecture and version) using just the common name of the game and publisher ID by enumerating `HKEY_CLASSES_ROOT\Local Settings\Software\Microsoft\Windows\CurrentVersion\AppModel\Repository\Families\{common_name}_{publisher_id}`.  The common name and Publisher ID should be constant, so that will help in case any updates are ever put out, instead of having to enumerate through the package full names.  Probably not an issue for any of the current games installed, but when TES6 comes out I'm betting they'll push updates and those PackageFullName's will change with each.

I'm currently writing all this up in a wiki page, then I'll push that improvement.

For the language....I haven't been able to find anything in the registry or root mutable location to help.  It seems the Windows Store uses the system default language to choose which version to launch (only applicable to Morrowind, and maybe Oblivion - checking that one now), since they had different binaries and everything per version.  Not applicable to Skryim+ since those handle language on an application level so they only ever had one release version.

So at this point I'm thinking hard code a language->directory map, then use the system language to choose which to look for.  User's might want to mod different languages though, so we might instead just want to show all three versions.

Speaking of, the number of game installs now is getting out of hand, we probably want to change the boot popup to a combobox with icons, otherwise that will get out of control.

**Comment by Infernio** [comment]
> I found a slight improvement to finding the mutable location

Nice, thanks! And yeah, we should really start a wiki page for all this.

> we probably want to change the boot popup to a combobox with icons

Agreed. I'll hash up a prototype for this tomorrow. Plus the dynamic sizing of that thing has always annoyed me.

**Comment by Infernio** [comment]
One more thing, the wiki page should be titled '[dev] Microsoft Store Games' since it's intended for developers.

**Comment by lojack5** [comment]
Got it, Oblivion is still downloading, after I tinker with that I'll get on that code push.

**Comment by lojack5** [comment]
Ok, looks like we got game detection hammered out, and the new game select popup looks really good (minus the button icons).

Next issue I see is we need to rework where the `{game} Mods` folder and such are stored.  The current workaround is to use a `bash.ini` and change `sOblivionMods`, `sBashModData`, and `sInstallersData`.  I really don't like this, since the INI is a per-install of Wrye Bash, but then changing these make us use the same paths no matter which game we're managing.  This is not an issue if the user installs WB inside the game folder, but it'd be nice to Just Work(TM) out of the box.  So we need those paths configurable on a per-game basis, and we should think about using better defaults for them.  Ideally long term, we don't create those directories at all until until the first time the Installers Tab is selected, then show a popup asking for where that data should be stored.

Still thinking on the language issue for Morrowind and Oblivion.

**Comment by Infernio** [comment]
I've renamed `inf-585-windows-store` to `585-windows-store` so that you can push to it as well. Also added the separate GameInfo overrides for WS games, so you should no longer run into the problem of Skyrim VR/Enderal SE/etc. conflicting.

**Comment by lojack5** [comment]
Sounds good, when I've got time today I'll work more on it.

**Comment by Infernio** [comment]
Fixed the WS games getting detected via registry as well and went back to the previous quit button icon. Couldn't find a good one for the Launch button among the standards though (most standard icons look terrible on Windows :/), so I just used the WB icon:

![image](https://user-images.githubusercontent.com/2845240/111209000-bd8e3180-85cb-11eb-945c-9506426a3876.png)

**Comment by Infernio** [comment]
Also, heads up: I'm gonna force-push the branch once to fix up commit order.

**Comment by lojack5** [comment]
Ok, was just working on the registry stuff myself (it was detecting my WS and my Steam SkyrimSE as the same location).  I'll check it out 👍

**Comment by lojack5** [comment]
Potential hickup from Discord: It might be that a purchased install of the game vs a Game Pass sub install of the game use a different AppData location.  Investigating, but I'm not about to drop 30$ to purchase another copy of SSE.  It may also just have been updated to use that so who knows.  If that's the case I don't think it's Bethesda that did it, but rather Microsoft maps file system request from the game to actual locations in the file system.

**Comment by lojack5** [comment]
Ok, the whole write protected folders is kinda forcing the issue (bash.ini is not a good solution for a "single Bash to manage all games" approach).  I'm really failing to decide where a good default location to store mods archives for games is though.  Right now my initial thoughts are:

- Change the default location for most metadata we generate to `%LOCALAPPDATA\Wrye Bash\{game_name}\metadata` (or similar).  This would be:
    -  Things that end up in `dirs[u'modsBash']`: stuff like the mtime, size, crc for plugins, etc.  Currently overridden by `sBashModData` in the ini.
    -  Things that end up in `dirs[u'bainData']`: so all of the installer state info, crc, etc and bsa cached data.  Currently overridden by `sInstallersData` in the ini.
- Change the default location where the actual mod installers are stored.  This one I don't know the best option.  Maybe default to `%LOCALAPPDATA\Wrye Bash\{game_name}\Installers`.  Currently overriden by `sOblivionMods` in the ini.  What are other good locations for these?
    - Disadvantages are users will want to easily navigate to this folder, this is much more hidden.
    - Advantages are bypassing the whole file permission issues on windows store, and helping somewhat with the Program Files permission issues.
- Since we're at it, move the Saves data and Load Order and Settings dicts to LocalAppData as well?  At least the settings dict.

It'd be nice to swich ALL games over to this, but we'd have to provide backwards compatibility for the old locations (at least for a few versions).  Another option is to special case just the Windows Store games to these locations, with plans to migrate other games to these locations in the future.  Also long term provide a nice in-app GUI for setting these locations.  We could even give a first time popup for the installers location for the first time the Installers Tab is selected to configure it.

I don't want to go too deeply into this, since that's encroaching on #572 and #178 territory.

Thoughts?

**Comment by Infernio** [comment]
I don't think using AppData is a good idea, because most guides/tutorials suggest people navigate to the `Bash Installers` folders manually and drop packages in there that way. Plus if you launch WB with admin rights you can't even drop packages onto the Installers tab, because Windows does not allow an admin-elevated application and a non-admin-elevated application to communicate. So I think we have to keep all our settings/packages/etc. in a location that's easy for people to navigate to, and AppData is not that since it's hidden by default and so needs the magic `%AppData%` to be entered into Explorer.

I was thinking of moving the default locations for *only* the WS games to something like `My Documents\Wrye Bash\{game name}`.

**Comment by Utumno** [comment]
> I was thinking of moving the default locations for only the WS games to something like My Documents\Wrye Bash\{game name}.

Yep and then we might consider (after users recover and code is ready) to move other stuff there too but really #250

**Comment by XJDHDR** [comment]
For `bash.ini`, I would suggest adding a new setting that defines where the `Wrye Bash` folder is. For example, the default location is `%LOCALAPPDATA%\Wrye Bash\{game_name}`, `My Documents\Wrye Bash\{game name}` or whatever. When you set that ini value, these files will be found at `%IniSetting\{game name}`.

**Comment by lojack5** [comment]
I still feel like at least our settings and metadata should be in AppData.  That's pretty much standard for programs these days (and of course options for changing them via INI, etc).  My Documents seems like a good place for installers though.  Sounds like Utumno gives a vote for just doing this for WS games at the moment.

**Comment by Infernio** [comment]
I say we move all of it to My Documents, but only for WS games. We can revisit where we store settings (I agree, hiding the dat files from the user seems wise) as part of #178 and #250.

**Comment by Infernio** [comment]
@XJDHDR Those INI settings already exist, all we're talking about is picking different defaults for `sOblivionMods`, `sBashModData` and `sInstallersData` in the case of WS games.

**Comment by XJDHDR** [comment]
Why did Lojack say that "bash.ini is not a good solution" if those settings I mentioned already exist?

**Comment by Infernio** [comment]
The eventual goal is to have one WB install that can target multiple games via profiles (#250), a bash.ini that specifies paths for only one game is not really useful for such a goal. Doesn't have much to do with this immediate issue, it's far off.

**Comment by Utumno** [comment]
> I say we move all of it to My Documents, but only for WS games. We can revisit where we store settings (and I agree, eventually hiding the dat files from the user in something like AppData seems wise) as part of #178 and #250.

Yep +1

**Comment by Arthmoor** [comment]
I wish more game companies would use the My Documents/My Games folder the way Bethesda does. Much easier to deal with when you need to find something.

**Comment by lojack5** [comment]
Sounds like a general consensus then, if Infernio hasn't already taken care of it I'll work on it tonight after classes/work.

**Comment by Infernio** [comment]
I haven't started, no.

**Comment by Infernio** [comment]
Got started on tackling the Morrowind/Oblivion multi-language thing.

**Comment by Infernio** [comment]
![image](https://user-images.githubusercontent.com/2845240/111469682-453c8300-8727-11eb-9c83-371141c9e0c0.png)

**Comment by Infernio** [comment]
![image](https://user-images.githubusercontent.com/2845240/111471730-7e75f280-8729-11eb-840c-e5fb4d4bed06.png)

Morrowind WS launches 🎉

**Comment by Infernio** [comment]
Turns out the UAC detection broke in 1ef881329aa008334bec49c939b191b1bfb1e683. Fixed the problem, but now I'm getting this:
```
Traceback (most recent call last):
  File "bash\bash.py", line 264, in main
    _main(opts, wx_locale)
  File "bash\bash.py", line 400, in _main
    mopy=bass.dirs[u'mopy'])
  File "bash\balt.py", line 2242, in ask_uac_restart
    u'for more information.') % {u'readmePath': readme}])[0]
  File "bash\balt.py", line 338, in vistaDialog
    button, radio, checkbox = dialog.show(commandLinks)
  File "bash\env\windows.py", line 1064, in show
    _indirect(byref(conf), byref(button), byref(radio), byref(checkbox))
WindowsError: exception: access violation writing 0x0000000000000000
```
It's failing to display the TaskDialog with the restart button for some arcane reason.

**Comment by Infernio** [comment]
Launching WB for SSE WS with admin rights works, but all the DLCs show up as missing strings.

**Comment by Infernio** [comment]
This is still wrong:
```
loot_parser.py   83 __init__: Using these LOOT paths:
loot_parser.py   84 __init__:  Masterlist: C:\Users\Infernio\AppData\Local\Packages\BethesdaSoftworks.SkyrimSE-PC_3275kfvn8vcwc\LocalCache\Local\LOOT\Skyrim Special Edition\masterlist.yaml
loot_parser.py   85 __init__:  Userlist: C:\Users\Infernio\AppData\Local\Packages\BethesdaSoftworks.SkyrimSE-PC_3275kfvn8vcwc\LocalCache\Local\LOOT\Skyrim Special Edition\userlist.yaml
loot_parser.py   86 __init__:  Taglist (fallback): E:\Infernio\Desktop\Programming\wrye-bash\Mopy\taglists\SkyrimSE\taglist.yaml
```
Those should be using the LOOT LocalAppData path, i.e. `C:\Users\Infernio\AppData\Local\LOOT\Skyrim Special Edition`.

**Comment by Infernio** [comment]
Almost done with the two-way LO management for SSE/FO4.

**Comment by lojack5** [comment]
Nice work, was about to update the language dirs for Oblivion but saw you already got them.  I'll take a look at the task dialog stuff (just finished an exam, about to start work - but hopefully will have some downtime to tinker).

**Comment by lojack5** [comment]
I'm curious, is there a way to set modification times in a UAC way?  Right now that's the only thing holding Bash back from dealing with Oblivion WS in non-admin mode.

**Comment by Infernio** [comment]
Doubt it. And won't we need UAC anyways for stuff like creating the INI Tweaks folder, creating the BP or installing mods?

**Comment by lojack5** [comment]
Ok, yes there's a way to set file attributes using UAC: IFileOperation.  Bad news: both Utumno and I have tried to get the IFIleOperation interface working with python to no avail.  Using SHFileOperation only allows moving/deleting/etc.

And Yes to INI Tweaks, BP creating, but those use SHFileOperation so the user will get an elevation prompt for those particualar operations, but Bash itself wont be running as admin.

**Comment by Infernio** [comment]
Guess we'll just have to tell people to run WB as admin for now then 🤷‍♀️

**Comment by lojack5** [comment]
Well actually I should specify: we failed to get IFileOperation working for moves/renames/etc in an *atom* way, because we'd have to do some weird internal tinkering stuff the deal with non-existent destination directories.  Unfortunately those tinkering ways aren't exposed to us in pywin32.

We should be able to get file attributes working though, I'll see how hard that will be.

**Comment by lojack5** [comment]
Here's some code I had written at the time when trying to get it all working:

https://gist.github.com/lojack5/ce3c0944052676f72ba2ba89ce3aa84f

**Comment by Infernio** [comment]
@lojack5 Do you have FO4 MS installed? I literally don't have enough hard drive space left for it :/
I need to know if my fsName is correct (Fallout4 MS) and if the two-way LO management I implemented works correctly for it.

**Comment by lojack5** [comment]
I did, but uninstalled it to get Oblivion installed, takes freaking 30GB since it ships ALL FOUR versions of the game.  Same issue as you, not enough HD space.  Plus no matter how hard I tell the Xbox App to install to my other hard-drive with PLENTY of space, it still installs to my C drive, an older SSD with only 125 GB total space to begin with.

/rant

Anyway, I did have it installed earlier, it is: `Fallout4 MS` for My Games (that folder hung around), So I'll say yes to being that in AppData, etc.  If we really need to I can uninstall Oblivion to install FO4 though.

**Comment by Infernio** [comment]
Thanks. Ran into another problem, for some reason I can't access the Morrowind.exe that comes with the WS version. Like, entirely - not just via WB, I can't even access the file when I open the folder in Windows Explorer.
I took out the check for game_detect_files because that made the game detection fail entirely (it checks for Morrowind.exe). Now it just means that the game launch button in the status bar is missing, not the end of the world. Does the same thing happen with your Morrowind installation?

**Comment by Infernio** [comment]
When I double-click, I get this:

![image](https://user-images.githubusercontent.com/2845240/111537484-c9b0f500-876b-11eb-9d48-9232d64a4135.png)

Python reports error 850.

**Comment by lojack5** [comment]
I actually have a similar but different issue.  I cannot launch ANY WS game from the filesystem.  Probably due to whatever weird emulation/linking the system does to point to the actual files in the virtual file system.

**Comment by lojack5** [comment]
No issues with detecting Morrowind.exe though, or other games.  I'll check if you have those checks disabled right now on the version of the branch on my local computer.

**Comment by Infernio** [comment]
I pushed a fixup for the two-way LO management, forgot to return the LO I get from the parent 🤦‍♀️

**Comment by Infernio** [comment]
That seems to have done it though, at least for SSE WS we now read the fallback location if the primary is missing and keep both in sync when writing just in case.

**Comment by lojack5** [comment]
Looks like exe/file detection in general might be trickier than we though for WS games.  Here's what happens when I do a "SkryimSSE.exe".exists() (in py3 but still)

```[WinError 650] The device object parameter is either not a valid device object or is not attached to the volume specified by the file name: 'C:\\Program Files\\ModifiableWindowsApps\\Skyrim Special Edition (PC)\\SkyrimSE.exe'```

**Comment by Infernio** [comment]
Yeah, same for the Morrowind EXE, see my edit in https://github.com/wrye-bash/wrye-bash/issues/585#issuecomment-801438030.

**Comment by lojack5** [comment]
Found the commands we need to run to launch them, still doesn't help for *reading* the executable though:

`start shell:AppsFolder\BethesdaSoftworks.SkyrimSE-PC_3275kfvn8vcwc!Game`

So in general `start shell:AppsFolder\{package_name}!Game`, where package_name is the string that has `{app_name}_{publisher_id}`, currently cached in `GameInfo.Ws._package_name`.

**Comment by Infernio** [comment]
>  Add detection for MS Store specific files, for example appxmanifest.xml

Do we need anything from appxmanifest.xml? There's the fsName `Skyrim Special Edition (PC)` in there, but we have that hardcoded already.

**Comment by lojack5** [comment]
Was just about to comment about that yep.  `appxmanifest.xml` is where you get the `!Game` from for the launch command.  We might also need to parse that for version info since we cannot access the EXEs.

**Comment by lojack5** [comment]
This line here in the app manififest:
```<Application Id="Game" Executable="SkyrimSELauncher.exe" EntryPoint="Windows.FullTrustApplication">```
Gives us the info for the command.  We can either assume it'll be `!Game` or parse it for that info.

There's also
```<Identity Name="BethesdaSoftworks.SkyrimSE-PC" Publisher="CN=21E520D9-F467-4438-A16E-79ADDBE4ECB1" Version="1.11.0.0" ProcessorArchitecture="x64" />```
Which of course we already know all that from our rummaging in the Windows Registry, but that might be the closest thing to a reliable version string for the game that we can get.

**Comment by Infernio** [comment]
If we don't have to parse XML, I'd rather not. It's a pain in py2 because it auto-encodes everything it can into ASCII as a `str` while leaving everything else as `unicode`. See `_xml_decode` in `fomod.py`.

**Comment by lojack5** [comment]
Yeah I don't think we need anything *new* from the xml file, we can hardcode the command to use `!Game`, and the info we've already found previously.  I think for the launcher buttons it'd suffice to check for the existence of `appmanifest.xml` to see if the game can be launched, since really the EXE doesn't even need to exist there to launch it with that command.

**Comment by Infernio** [comment]
How do you run that `start shell:AppsFolder\BethesdaSoftworks.SkyrimSE-PC_3275kfvn8vcwc!Game` from Python? I tried subprocess.Popen, but that just errors out saying it can't find the file.

**Comment by lojack5** [comment]
I'll give it a shot, probablly need to pass shell=True to Popen or whatever that option is.

**Comment by Infernio** [comment]
Already tried, that doesn't launch it or give an error, it just beeps 🤷‍♀️

**Comment by lojack5** [comment]
Huh, yeah I'm not sure how to get that to work from python, I'll keep tinkering.

**Comment by lojack5** [comment]
Ok, wierd, from the interactive interpreter it didnt work, but running this worked fine:

```python
import subprocess as sub

app = 'BethesdaSoftworks.SkyrimSE-PC_3275kfvn8vcwc!Game'

cmd = ['start', 'shell:AppsFolder\\%s' % app]

p = sub.Popen(cmd, shell=True)
```

**Comment by Infernio** [comment]
Oh, I was using a forward slash 🤦‍♀️ 
Works fine now.

**Comment by Infernio** [comment]
Anything else left open or is this ready for nightly now?

**Comment by lojack5** [comment]
I think it's good for testing?  I'm sure we'll find out quick if it isnt.  Need readme updates but other than that good for testing yeah?

**Comment by lojack5** [comment]
Hmm, I suppose one note: Wizards will fail if they check against the game version.

**Comment by Infernio** [comment]
Yeah, there's surely a few kinks left to smooth out. But let's get some testing on it while we sort those out.

**Comment by lojack5** [comment]
We're going to have to rework `GameInfo.game_detect_files` for Windows Store games, since the EXEs technically don't exist in the target directory.  Effect of this is launching with `-o` doesn't actually set the game.

**Comment by lojack5** [comment]
Ok, other than readme updates, I can't think of anything else to add for WS games.

**Comment by lojack5** [comment]
Ok, finished up remaining issues I could find, edited the readme.  I'm going to rewrite history on `585-windows-store` to sqaush fixups and such.

**Comment by Infernio** [comment]
The version stored in the appxmanifest.xml doesn't make any sense. For Morrowind it's 1.0.0.0 but shows up ingame as 1.6.1820, for SSE it's 1.11.0.0 but shows up ingame as 1.5.111.0.8.
I guess we'll just have to note in the docs that we only have that as an approximation for WS games?

**Comment by Infernio** [comment]
What's weird is that I *can* access the Details tab for the executable through Windows Explorer and it shows the right version there.

**Comment by Infernio** [comment]
Did Microsoft change something? `get_file_version` actually works for my copies of the executables:

![image](https://user-images.githubusercontent.com/2845240/111996378-405a4380-8b1a-11eb-8642-5a6ba4797eb2.png)

![image](https://user-images.githubusercontent.com/2845240/111996827-b2cb2380-8b1a-11eb-978e-34df93cde11e.png)

**Comment by lojack5** [comment]
Huh, interesting. Maybe SKSE will work too, seems like the only real reason to do it.

I'll check it out when I get home today (jury duty all week).

**Comment by lojack5** [comment]
Ok, yep I'm seeing the same thing.  `skse_launcher.exe`  is still inaccessible, I'm guessing they have to provide specific exceptions to what EXEs are allowed to be accessible.  I still cannot launch the game with the EXEs, but thankfully we have that alternate method to launch.

So I guess we either remove the manifest version parsing entirely, or keep it as a fallback from the usual method in case they change things again.

**Comment by Infernio** [comment]
I'd say we keep the parsing code around for now in case they change it again, but change the actual version detection in wizards, FOMODs and tooltips back to using the EXE.

**Comment by lojack5** [comment]
Ok, done.  I simply made it use the usual method, and fallback to the new method if an error occurs.  However on second though (future looking) maybe we add an attribute to GameInfo indicating which version detection method to use?  That way if we want to support some games that we can't parse the EXE and some we can, we can define that directly in the game support file.

**Comment by Infernio** [comment]
Let's keep it as a fallback for now, no need to fatten up GameInfo even further :)

**Comment by Infernio** [comment]
My EXEs are back to denying me access again 🤔
I've adjusted the fallback a bit so it also takes over if the version detected is (0, 0, 0, 0), which is what we get if pywin32 reports an error.

**Comment by Infernio** [comment]
Went ahead and merged it, even normal game branches start collecting regressions at an amazing pace - and this is no normal game merge :P

**Comment by lojack5** [comment]
> My EXEs are back to denying me access again 🤔

Same, oh Micro/Beth...le sigh.  And sounds good to all the rest :)

**Comment by Arthmoor** [comment]
They're really making changes to the exe this often?

**Comment by Infernio** [comment]
Might just be Windows weirdness where it works sometimes, then you reboot and it goes back to not working anymore 🤷‍♀️

**Comment by Infernio** [comment]
So, someone reported a *third* path for plugins.txt that their SSE install is using:
```
D:\WpSystem\S-1-5-21-1129048686-3227679809-3769424873-1001\AppData\Local\Packages\BethesdaSoftworks.SkyrimSE-PC_3275kfvn8vcwc\LocalCache\Local\Skyrim Special Edition MS
```

While we're trying to use
```
C:\Users\jcain\AppData\Local\Packages\BethesdaSoftworks.SkyrimSE-PC_1.11.0.0_x64__3275kfvn8vcwc\LocalCache\Local\Skyrim Special Edition MS
```

And so the game isn't seeing the changes WB is making to the load order.

Full comment from Discord:

> I pulled down the latest build and tried it out. I have been working through the location of plugins.txt. I had found the one modified by Wyre Bash is different from what is used by SSE. I see the new build uses C:\Users\jcain\AppData\Local\Packages\BethesdaSoftworks.SkyrimSE-PC_1.11.0.0_x64__3275kfvn8vcwc\LocalCache\Local\Skyrim Special Edition MS. However, I have SSE installed on my D: drive and it is using D:\WpSystem\S-1-5-21-1129048686-3227679809-3769424873-1001\AppData\Local\Packages\BethesdaSoftworks.SkyrimSE-PC_3275kfvn8vcwc\LocalCache\Local\Skyrim Special Edition MS. I also noticed that I have a C:\Users\jcain\AppData\Local\Packages\BethesdaSoftworks.SkyrimSE-PC_3275kfvn8vcwc directory which contains directory links to D:\WpSystem\S-1-5-21-1129048686-3227679809-3769424873-1001\AppData\Local\Packages\BethesdaSoftworks.SkyrimSE-PC_3275kfvn8vcwc. So because of the Package name difference, it continues to not to update the version used by SSE. Not sure on the differences in the names and whether is varies based on installing in D:, but thought this info might be of help.

**Comment by sibir-ine** [comment]
Just a heads up, Ortham implemented support for the Microsoft Store/GamePass versions in LOOT a few days ago, & we found out that Microsoft has changed how the games are installed by default. It's mostly detailed in https://github.com/loot/loot/issues/1436, but, in summary, the install directories are no longer stored in the registry, but they are now stored in a file, `.GamingRoot`, in the root of the drive they're installed to. However, this file only stores the directory in which all games installed through the Xbox app are installed. The folder names defined here:

https://github.com/loot/loot/blob/c5589df8139b85e2277fb129d0989e3bf6645b32/src/gui/state/game/game_detection.cpp#L345-L369

& the localization sub-folders for older games (which appear to be the same as the old MS installs) defined here:

https://github.com/loot/loot/blob/c5589df8139b85e2277fb129d0989e3bf6645b32/src/gui/state/game/game_detection.cpp#L197-L230

can be used to find each game's full install path. Ortham also described the contents & encoding of `.GamingRoot` here:

https://github.com/loot/loot/blob/e631685afa201bbcd2c4293428f67ea51f1d12fd/src/gui/helpers.cpp#L361-L363

Other notable differences are that these new install paths don't appear to be locked down as tightly as before. I can freely install & uninstall mods for MS Morrowind via WB without any elevated permissions, & LOOT can modify timestamps just the same. However, the executables seem to be completely locked down; we can't read version numbers whatsoever to evaluate conditions involving them, so we had to implement workarounds to short circuit the conditions for MS games.

The newer versions also appear to favor the secondary `plugins.txt` locations listed in the wiki page, but I'm not sure as I don't have any of the MS games that use it. I don't think they even use the primary locations anymore.

**Comment by Infernio** [comment]
Oh god no, they changed it *again*?? 😞

Does it still make sense to keep the old detection method around then?

**Comment by sibir-ine** [comment]
I'm not sure how heavily enforced the new directories are, so it might be worth keeping around for legacy reasons. In our testing, we had to manually update the Xbox app through the Microsoft Store before it started installing them there, & I'm not sure if it automatically moves the games (we all manually reinstalled the games after the update without getting a chance to test unfortunately), so some users may still be using the old locations. Ortham ended up keeping it.

**Comment by lojack5** [comment]
Well I no longer have game pass, so I can't really test any changes. Microsoft can be so annoying.  Is there at least a way to determine programmatically which drives have a `.GamingRoot` without just blindly parsing every drive?  That could be slow especially with mapped network drives or harddrives that spin down when not in use.

**Comment by Ortham** [comment]
> Is there at least a way to determine programmatically which drives havei a `.GamingRoot` without just blindly parsing every drive?

Not that I know of, LOOT just checks every drive once on startup - I've got an external HDD and spinning it up to check didn't noticeably impact the startup time (though obviously not checking it unnecessarily would be better). 

I did have a look around to see if I could spot where the Xbox app keeps its settings, but couldn't find anything mentioning drive letters.

**Comment by Infernio** [comment]
Opened an issue for adding support this in 311: #639
